spring:
  cloud:
    gateway:
      routes:
        - id: service-one
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/**

server:
  port: 9000
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
