spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/api/v1/**
        - id: media-catalog-service
          uri: lb://MEDIA-CATALOG-SERVICE
          predicates:
            - Path=/mcs/**

server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
