spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://localhost:8099
          predicates:
            - Path=/api/v1/**
  application:
    name: api-gateway-service

server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
