spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${DB_SERVER_URL:localhost:5438/auth-serv-db}
    username: ${DB_SERVER_USERNAME:postgres}
    password: ${DB_SERVER_PASSWORD:password}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

# media.catalog.service.url: MEDIA-CATALOG-SERVICE