spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
#   data:
#     redis:
#       host: ${REDIS_HOST}
#       port: ${REDIS_PORT}
#   datasource:
#     url: jdbc:postgresql://${DB_SERVER_URL}
#     username: ${DB_SERVER_USERNAME}
#     password: ${DB_SERVER_PASSWORD}

# jwt:
#   secret:
#     access: ${JWT_ACCESS}
#     refresh: ${JWT_REFRESH}