spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_SERVER_URL:localhost:5439/media-catalog-serv-db}
    username: ${DB_SERVER_USERNAME:postgres}
    password: ${DB_SERVER_PASSWORD:password}

payment.redirect.url: /success-page

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}