spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_SERVER_URL:localhost:5439/media-catalog-serv-db}
    username: ${DB_SERVER_USERNAME:postgres}
    password: ${DB_SERVER_PASSWORD:password}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: 5672
    username: user
    password: password

payment.redirect.url: /success-page

download:
  path: ${DOWNLOAD_PATH:http://localhost:8083/s3/api/v1/download?name=}
queue:
  name: queue
msg:
  subject: Tune Vault
default:
  logo:
    uri: default-logo-uri.jpg

grpc:
  client:
    payment-service:
      address: discovery:///PAYMENT-SERVICE?grpc-port=9090
      negotiation-type: plaintext

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}