apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-service-redis
  name: auth-service-redis
  namespace: default
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: auth-service-redis
  type: ClusterIP